---
name: Basic libarary configuration
variables:
  root_passwd: redhat
  user:
      name: localuser1
      passwd: "654321"
      pin: "123456"
configs:
  dir: conf/ # relative to the file or full path lik /root/conf
