---
- hosts: vm
  become: true
  remote_user: root
  vars:
    virt: /root/virt_card
    conf: "{{ virt }}/conf"
  tasks:
    - name: Create necessary directories
      file:
        path: "{{ virt }}"
        state: directory

    - name: Copy configs
      copy:
        src: conf
        dest: "{{ virt }}"

    - name: Run setup of local CA
      script: setup_ca.sh -d "{{ virt }}"

    - name: Run setup of virtual smart card
      script: setup_virt_card.sh -c "{{ conf }}" -v "{{ virt }}"

    - name: Install python packages
      pip:
        name:
          - pexpect
          - avocado-framework
